
#include                  = 
#define                   = 
#integrator               = md
tinit                    = 0    # 
dt                       = 0.002 # 
nsteps                   = 2500000 # 
init_step                = 0       # 
simulation_part          = 1       # 
#comm_mode                = Linear
nstcomm                  = 100  # 
#comm_grps                = System
bd_fric                  = 0    # 
ld_seed                  = 1993 # 
emtol                    = 10   # 
emstep                   = 0.01 # 
niter                    = 20   # 
fcstep                   = 0    # 
nstcgsteep               = 1000 # 
nbfgscorr                = 10   # 
rtpi                     = 0.05 # 
nstxout                  = 500  # 
nstvout                  = 500  # 
nstfout                  = 0    # 
nstlog                   = 25000 # 
nstcalcenergy            = 100   # 
nstenergy                = 500   # 
nstxtcout                = 25000 # 
xtc_precision            = 1000  # 
#xtc_grps                 = 
#energygrps               = Solute Solvent
#cutoff_scheme            = Group
nstlist                  = 5    # 
#ns_type                  = Grid
#pbc                      = xyz
periodic_molecules       = no   # 
verlet_buffer_drift      = 0.005 # 
rlist                    = 1.2   # 
rlistlong                = -1    # 
nstcalclr                = -1    # 
#coulombtype              = PME-switch
#coulomb_modifier         = Potential-shift-Verlet
rcoulomb_switch          = 0    # 
rcoulomb                 = 1.1  # 
epsilon_r                = 1    # 
epsilon_rf               = 0    # 
#vdwtype                  = shift
#vdw_modifier             = Potential-shift-Verlet
rvdw_switch              = 0.9  # 
rvdw                     = 1.0  # 
#DispCorr                 = EnerPres
table_extension          = 1    # 
#energygrp_table          = 
fourierspacing           = 0.125 # 
fourier_nx               = 0     # 
fourier_ny               = 0     # 
fourier_nz               = 0     # 
pme_order                = 4     # 
ewald_rtol               = 1e-05 # 
#ewald_geometry           = 3d
epsilon_surface          = 0    # 
optimize_fft             = yes  # 
implicit_solvent         = No   # 
#gb_algorithm             = Still
nstgbradii               = 1    # 
rgbradii                 = 1    # 
gb_epsilon_solvent       = 80   # 
gb_saltconc              = 0    # 
gb_obc_alpha             = 1    # 
gb_obc_beta              = 0.8  # 
gb_obc_gamma             = 4.85 # 
gb_dielectric_offset     = 0.009 # 
#sa_algorithm             = Ace-approximation
sa_surface_tension       = -1   # 
#tcoupl                   = v-rescale
nsttcouple               = 5    # 
nh_chain_length          = 10   # 
print_nose_hoover_chain_variables = no # 
#tc_grps                  = Solute Solvent
tau_t                    = 0.1 0.1 # 
ref_t                    = 500 500 # 
#pcoupl                   = no
#pcoupltype               = Isotropic
nstpcouple               = 5    # 
tau_p                    = 1.0  # 
compressibility          = 4.5e-5 # 
ref_p                    = 1      # 
refcoord_scaling         = No     # 
QMMM                     = no     # 
QMMM_grps                =        # 
QMmethod                 =        # 
#QMMMscheme               = normal
QMbasis                  =      # 
QMcharge                 =      # 
QMmult                   =      # 
SH                       =      # 
CASorbitals              =      # 
CASelectrons             =      # 
SAon                     =      # 
SAoff                    =      # 
SAsteps                  =      # 
MMChargeScaleFactor      = 1    # 
bOPT                     =      # 
bTS                      =      # 
annealing                =      # 
annealing_npoints        =      # 
annealing_time           =      # 
annealing_temp           =      # 
#gen_vel                  = no
#gen_temp                 = 300
#gen_seed                 = 173529
#constraints              = all-bonds
#constraint_algorithm     = Lincs
#continuation             = no
Shake_SOR                = no   # 
shake_tol                = 0.0001 # 
lincs_order              = 4      # 
lincs_iter               = 2      # 
lincs_warnangle          = 30     # 
#morse                    = no
energygrp_excl           =      # 
nwall                    = 0    # 
wall_type                = 9-3  # 
wall_r_linpot            = -1   # 
wall_atomtype            =      # 
wall_density             =      # 
wall_ewald_zfac          = 3    # 
pull                     = no   # 
rotation                 = no   # 
disre                    = No   # 
#disre_weighting          = Conservative
disre_mixed              = no   # 
disre_fc                 = 1000 # 
disre_tau                = 0    # 
nstdisreout              = 100  # 
orire                    = no   # 
orire_fc                 = 0    # 
orire_tau                = 0    # 
orire_fitgrp             =      # 
nstorireout              = 100  # 
free_energy              = no   # 
#couple_moltype           = 
#couple_lambda0           = vdw-q
#couple_lambda1           = vdw-q
couple_intramol          = no   # 
init_lambda              = -1   # 
init_lambda_state        = -1   # 
delta_lambda             = 0    # 
nstdhdl                  = 50   # 
fep_lambdas              =      # 
mass_lambdas             =      # 
coul_lambdas             =      # 
vdw_lambdas              =      # 
bonded_lambdas           =      # 
restraint_lambdas        =      # 
temperature_lambdas      =      # 
calc_lambda_neighbors    = 1    # 
init_lambda_weights      =      # 
dhdl_print_energy        = no   # 
sc_alpha                 = 0    # 
sc_power                 = 1    # Real
sc_r_power               = 6    # Real
sc_sigma                 = 0.3  # Real
sc_coul                  = no   # 
separate_dhdl_file       = yes  # 
dhdl_derivatives         = yes  # 
dh_hist_size             = 0    # Real
dh_hist_spacing          = 0.1  # Real
acc_grps                 =      # 
accelerate               =      # 
freezegrps               =      # 
freezedim                =      # 
cos_acceleration         = 0    # Real
deform                   =      # 
simulated_tempering      = no   # 
#simulated_tempering_scaling = geometric
sim_temp_low             = 300  # Real
sim_temp_high            = 300  # Real
E_x                      =      # 
E_xt                     =      # 
E_y                      =      # 
E_yt                     =      # 
E_z                      =      # 
E_zt                     =      # 
adress                   = no   # ??
user1_grps               =      # groupnames
user2_grps               =      # groupnames
userint1                 = 0    # Integer
userint2                 = 0    # Integer
userint3                 = 0    # Integer
userint4                 = 0    # Integer
userreal1                = 0    # Real
userreal2                = 0    # Real
userreal3                = 0    # Real
userreal4                = 0    # Real
